export default function TermsPage() {
  return (
    <div style={{ minHeight:"100vh", background:"#0A0A0A", color:"#F0F0F0", padding:"60px 24px" }}>
      <div style={{ maxWidth:760, margin:"0 auto" }}>
        <div style={{ fontSize:"1.4rem", fontWeight:800, color:"#D97B4F", marginBottom:8, fontFamily:"monospace", letterSpacing:".1em" }}>JUNKPIX</div>
        <h1 style={{ fontSize:"2rem", fontWeight:800, marginBottom:8 }}>Terms of Service</h1>
        <p style={{ color:"#666666", fontSize:".84rem", marginBottom:40 }}>Last updated: June 30, 2026</p>

        <div style={{ display:"flex", flexDirection:"column", gap:28, fontSize:".92rem", lineHeight:1.7, color:"#ccc" }}>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>1. Agreement to Terms</h2>
            <p>By creating an account or using JunkPix ("the Service"), operated by The GO TO Junk Removal LLC ("we," "us," "our"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>2. Description of Service</h2>
            <p>JunkPix is a software platform that allows junk removal operators to receive AI-generated photo-based quotes from customers, manage jobs, track costs, and communicate with customers via email and other channels. JunkPix is a software tool only; we are not a party to any transaction between an operator and their customers.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>3. Accounts</h2>
            <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials and for all activity under your account. You must be at least 18 years old to use the Service.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>4. Subscription and Billing</h2>
            <p>JunkPix offers paid subscription plans billed monthly. A free trial period may be offered. By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel. You may cancel at any time from your account settings; cancellation takes effect at the end of the current billing period. Fees are non-refundable except where required by law.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>5. AI-Generated Estimates</h2>
            <p>Price estimates generated by JunkPix's AI are based on photos and information provided and are intended as a starting point only. Operators are solely responsible for reviewing, adjusting, and confirming final pricing before communicating it to customers. JunkPix does not guarantee the accuracy of any AI-generated estimate.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>6. Customer Communications</h2>
            <p>If you use JunkPix to send emails, text messages, or other communications to your customers, you are solely responsible for obtaining all necessary consent from those customers and complying with applicable laws, including the Telephone Consumer Protection Act (TCPA) and CAN-SPAM Act. You agree not to use the Service to send unsolicited or non-compliant communications.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>7. User Content</h2>
            <p>You retain ownership of photos, business information, and other content you upload ("User Content"). By uploading User Content, you grant JunkPix a license to store, process, and display that content as necessary to provide the Service, including using photos for AI analysis and optional social media content generation.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>8. Prohibited Uses</h2>
            <p>You may not use the Service for any unlawful purpose, to harass or defraud customers, to upload content you do not have rights to, or to attempt to disrupt or reverse-engineer the Service.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>9. Termination</h2>
            <p>We may suspend or terminate your account at any time for violation of these Terms. You may close your account at any time through your account settings.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>10. Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" without warranties of any kind, express or implied. We do not guarantee the Service will be uninterrupted, error-free, or that AI-generated content will be accurate.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>11. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, JunkPix and The GO TO Junk Removal LLC shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to lost profits, lost business, or pricing disputes with your customers.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>12. Changes to These Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 style={{ fontSize:"1.1rem", fontWeight:700, color:"#F0F0F0", marginBottom:10 }}>13. Contact</h2>
            <p>Questions about these Terms can be sent to <a href="mailto:junkpixapp@gmail.com" style={{ color:"#D97B4F" }}>junkpixapp@gmail.com</a>.</p>
          </section>

        </div>
      </div>
    </div>
  );
}
